### ISSUE TITLE
Allow displaying more than 1 photo at a time

### ISSUE THREAD

**Issue by mvexel** [openstreetcam/josm-plugin#12]
The ability to see 3 or 5 photos in the same time will allow us to find faster a representative image then clicking each image to see in what image you will have the signpost information.

Also, this will be useful integration when combined with maproulette, because the user will download a task were he has to add missing signpost informations.

We know that we have OSV data, so we present the image that is the closest to the node that have the highway=motorway_junction and will also download 2 more images to the left and the right of the imagery,(in the mockup i show the example with only one image to the left and right)

**Comment by beataj-telenav** [comment]
Thanks for the idea, we added to the plugin suggestion list. The plugin logic is based on displaying only one photo and we don't plan to change this behavior soon.
