### ISSUE TITLE
Images are not cached

### ISSUE THREAD

**Issue by grischard** [openstreetcam/josm-plugin#13]
When going back and forth between two images, both images will be re-downloaded every time. This can make things tedious on a slow connection.

It would be good if the plugin used a caching mechanism for thumbnails and full images. Maybe the caching mechanism JOSM uses for tiles can be used.

**Comment by mvexel** [comment]
We are working on a caching mechanism, @grischard .

**Comment by mvexel** [comment]
The are cached now!

**Comment by grischard** [comment]
Thank you! I think this can be closed then.
