### ISSUE TITLE
Nagging error message when JOSM is temporarily offline

### ISSUE THREAD

**Issue by ltog** [openstreetcam/josm-plugin#14]
When I use JOSM and the Internet connection is temporarily offline, the plugin displays an annoying error messages which is recreated every minute or so:

Title of the message: `Error retrieving images from OpenStreetView service`
Message: `com.telenav.josm.common.http.HttpConnectorException: Could not connect.`

I suggest to not display this message or at least display it only once and tell the user that it won't be displayed again (until there is a connection that then breaks again).

**Comment by mvexel** [comment]
@ltog thanks -- I had noticed that too. We will work on removing it (unless you have Java skills and can submit a PR?)

**Comment by ltog** [comment]
@mvexel : Thanks!

I do have some Java skills, but unfortunately I am quite busy at the moment. :-\

**Comment by beataj-telenav** [comment]
Thanks for reporting the issue. We will remove it in future releases. It should not take to much time, since it is relatively easy to implement.

**Comment by ltog** [comment]
@beataj-telenav : Cool, thank you!

**Comment by mvexel** [comment]
@beataj-telenav this was implemented, correct?

**Comment by beataj-telenav** [comment]
Yes, we have implemented this feature request.
