### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by FouadAstitou** [openstreetcam/josm-plugin#16]
Hi,
Is there an api for accessing the images to download them?

Thanks in advance and keep up the great work!

**Comment by mvexel** [comment]
There is an API, but we have not advertised it very much yet. Email hello@openstreetcam.org if you want to give it a try. Please let us know what you intend to use it for.

**Comment by FouadAstitou** [comment]
Hi Martijn,

Sorry for only getting back to you now.
We are working on a travel app and we want to use the pictures for our POIs.

If you need more info, just let me know.

Best regards,
Fouad
