### ISSUE TITLE
OSC josm-plugin crashes in josm version 12743+ (gui.JosmUserIdentityManager is now deprecated)

### ISSUE THREAD

**Issue by skorasaurus** [openstreetcam/josm-plugin#18]
Using a development version of JOSM v. 12767; I immediately receive a bug upon opening josm and I think it's triggered by the openstreetcam. 

the full error message is at https://gist.github.com/skorasaurus/4209d5d888b16590033432bc269f8d80 
but the relevant part which leads me to believe that OSC is the culprit is the following [line 53](https://gist.github.com/skorasaurus/4209d5d888b16590033432bc269f8d80#file-gistfile1-txt-L53) : 

```java.lang.NoClassDefFoundError: org/openstreetmap/josm/gui/JosmUserIdentityManager
at org.openstreetmap.josm.plugins.openstreetcam.argument.UserAgent.<init>(UserAgent.java:33)
```
I also noticed that in a [recent  version of josm, 12743](https://josm.openstreetmap.de/changeset/12743/josm) gui.JosmUserIdentityManager is deprecated.

**Comment by beataj-telenav** [comment]
Thanks for reporting the issue. We are working on fixing the issue as soon as possible.

**Comment by beataj-telenav** [comment]
The issue was fixed in build 105.
