### ISSUE TITLE
'Created on null' message

### ISSUE THREAD

**Issue by ltog** [openstreetcam/josm-plugin#19]
When opening the 'OpenStreetCam' view in JOSM, the line above the picture says:

    Created on null by ...

While null probaby should stand for the date the picture was taken.

Some affected images:
- http://internal.openstreetcam.org/details/165281/2052
- http://internal.openstreetcam.org/details/170085/178

Regarding the second picture: This was taken by me using an old-school digital camera, not a smartphone. The date shown on http://internal.openstreetcam.org/details/170085/178 seems to be the upload date, not the date the picture was recorded. See also #4.

Not all pictures are affected from the "null" problem. E.g. http://internal.openstreetcam.org/details/51041/11040 shows the date. To be more precise: JOSM shows the date 2017-02-23, while openstreetcam.org shows "Mar 06, 2017".

Maybe "null" is shown for pictures that were not taken by a smartphone?

**Comment by beataj-telenav** [comment]
The issue was fixed.

**Comment by beataj-telenav** [comment]
The internal openstreetcam website displays the date when the track was uploaded not the date when it was recorded. Meanwhile we integrated the main openstreetcam details page link in the plugin and also the recorded date is displayed (info is returned by the openstreetcam API).  
The internal.openstreetcam website should not be used anymore.
