### ISSUE TITLE
Plugin does not remember layer state

### ISSUE THREAD

**Issue by TZornG** [openstreetcam/josm-plugin#20]
The plugin remembers if the OpenStreetCam layer was active or inactive last time JOSM ran. This works if the layer was deleted using right-klick - delete. If you close the layer with the recycle bin icon in the layers pane instead the layer will be re-activated again next time JOSM is started.

![openstreetcam layer closing](https://user-images.githubusercontent.com/16701177/37116853-b410acba-224f-11e8-8445-91a03e4157b5.jpg)

**Comment by beataj-telenav** [comment]
Thanks for reporting. The issue seams to be a JOSM core related issue.

**Comment by beataj-telenav** [comment]
Closing since this is a JOSM core issue, not an OSC plugin.
