### ISSUE TITLE
Issue with plugin, traffic sign detection, and JOSM

### ISSUE THREAD

**Issue by rich123** [openstreetcam/josm-plugin#21]
One of my tracks finally received "traffic sign detection" processing, and now I am encountering an odd bug in JOSM when using the OSC plugin to step along the track.

It seems that whenever I get close to a sign detection area, the entire JOSM display blanks out.  I'm running JOSM 13710 (current stable version) and the OSC plugin reports it is V 145 (I did try "updating plugins" before reporting, no new OSC plugin was downloaded.

A couple screen shots will help.

When this OSC image is the current OSC image in the OSC plugin, the map in JOSM is correct: http://openstreetcam.org/details/1184565/27/track-info

JOSM screenshot when current image is the URL above): 
![before-stepping](https://user-images.githubusercontent.com/305956/40587678-8f59abc0-61a0-11e8-842e-62eaf469332c.png)

But, if I press the "next image" button (or manually click on the OSC path location of the next image, which is this one: http://openstreetcam.org/details/1184565/28/track-info then I get this in JOSM:

![after-stepping](https://user-images.githubusercontent.com/305956/40587692-baffeb68-61a0-11e8-8753-ce0b78b378fb.png)

The entire map (background images, data layer, everything, disappears, except for that "stop" icon.

If I step "backwards" by using the "back arrow" in the OSC plugin, the original screen shot reappears (background images, map data, etc.).  The 'determinant' seems to be stepping close to the traffic sign detection here: http://openstreetcam.org/details/1184565/31/track-info

My reason for saying the above is because if I use the "step forward" arrow in the plugin to continue stepping forward to the next image without traffic sign metadata (here: http://openstreetcam.org/details/1184565/37/track-info) then the JOSM map reappears (background images, map data, OSC track) as if nothing had happened.  Note that all of the intervening OSC images show the "blank map" view in JOSM.

**Comment by mds08011** [comment]
I am experiencing the same problem when moving between images near a detected stop sign.  The track where the problem occurred: http://openstreetcam.org/details/1223643/2/track-info

**Comment by beataj-telenav** [comment]
Thank you for reporting the issue. We have found the issue and will fix it soon.

**Comment by beataj-telenav** [comment]
The issue was solved.
