### ISSUE TITLE
plugin is using the wrong URL for image load

### ISSUE THREAD

**Issue by smacqueen** [openstreetcam/josm-plugin#22]
The plugin uses:-
http://internal.openstreetcam.org/storage9/files/photo/2018/8/14/lth/1278583_e640d_5b72d3246b9a6.jpg
which returns not found
http://openstreetcam.org/storage9/files/photo/2018/8/14/lth/1278583_e640d_5b72d3246b9a6.jpg
returns the expected image.

The iphone app works correctly and the openstreetcam.org browser interface works correctly.

Any idea why?

Thanks

**Comment by beataj-telenav** [comment]
Thanks for reporting the issue with the images, we are looking into it.
The mobile app uses the "openstreetcam.org" API, while the plugin and also other components the "internal.openstreetcam.org" API. The 2 API instances are synchronized periodically and images should be visible on both of the API's/websites.

**Comment by beataj-telenav** [comment]
The issue was solved.
