### ISSUE TITLE
ampersand in username

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [openstreetcam/josm-plugin#25]
My username is &ergio, not ergio!

https://openstreetcam.org/user/ergio
https://www.openstreetmap.org/user/&ergio

![screenshot](https://user-images.githubusercontent.com/14617699/44426217-b67b2000-a596-11e8-8d70-704e78eda67a.png)

**Comment by beataj-telenav** [comment]
Thanks for reporting the issue. Aldo this is not a JOSM plugin bug, since the OSC plugin only displays the data received from the OpenStreetCam API.

**Comment by c-e-p-x-u-o** [comment]
Is this the same bug as https://github.com/openstreetcam/openstreetview.org/issues/173 ?

**Comment by alexandrui-telenav** [comment]
Yes
