### ISSUE TITLE
New images are not shown on the map as dots.

### ISSUE THREAD

**Issue by 532910** [openstreetcam/josm-plugin#27]
Open track, press edit (https://openstreetcam.org/details/1274477/59/edit-osm) -> josm.
Pres the fourth photo (plugin loads the track and show it):
![1](https://user-images.githubusercontent.com/14617699/44853471-beaa1e00-ac6e-11e8-9565-8144dae18697.png)

press next, and it loads next photo and selects next blue marker:
![2](https://user-images.githubusercontent.com/14617699/44853484-c36ed200-ac6e-11e8-91c9-c593b7805809.png)

press next, and it loads next photo but NO blue marker selected:
![3](https://user-images.githubusercontent.com/14617699/44853487-c669c280-ac6e-11e8-8970-c557f821fd1e.png)

**Comment by beataj-telenav** [comment]
Currently the OSC plugin works on the following way: if any OSM Data layer is active then the image locations on the map are displayed only for those images that belongs to the bounds of the active OSM Data layer.
