### ISSUE TITLE
"Only mine" checkbox unusable and no obvious guidance on how to enable it

### ISSUE THREAD

**Issue by pnorman** [openstreetcam/josm-plugin#31]
![image](https://user-images.githubusercontent.com/1190866/51150574-bfa5ab80-181b-11e9-8112-033696c576c3.png)

I can't check only mine, and there's no help text explaining how to enable this feature.

**Comment by mvexel** [comment]
Same for 'Not older than'.

This used to work.

**Comment by beataj-telenav** [comment]
@pnorman : The 'Only mine'  filter is applied only to the photo locations and individual detections and display only the photos that belong to the currently logged in user and detections that were manually added by the logged in user.  This filter can be used only if the user is logged in using OAuth. 
Could you provide the following information:

- OSC plugin version that you are using
- platform
- JOSM preferences.xml files

@mvexel: The 'Not older than' filters work only for big zoom levels (photo/detection view); this filter is disabled for small zoom levels (segment view) since the OpenStreetCam API does not offer support for this functionality.

**Comment by pnorman** [comment]
> * OSC plugin version that you are using

184

> * platform

Windows 10

> * JOSM preferences.xml files

I'd have to scrub them for privacy and security. Here are what I think the relevant parts are

```xml
  <tag key='oauth.access-token.key' value='...'/>
  <tag key='oauth.access-token.secret' value='...'/>

  <tag key='openstreetcam.dataType' value='ELEMENT'/>
  <tag key='openstreetcam.detection.panelOpened' value='true'/>
  <tag key='openstreetcam.error.detection.search.suppress' value='true'/>
  <tag key='openstreetcam.filter.changed' value='true'/>
  <tag key='openstreetcam.filter.onlyUserFlag' value='false'/>
  <maps key='openstreetcam.filter.search.editStatus'>
    <map>
      <tag key='name' value='OPEN'/>
    </map>
  </maps>
  <maps key='openstreetcam.filter.search.mode'>
    <map>
      <tag key='name' value='AUTOMATIC'/>
    </map>
    <map>
      <tag key='name' value='MANUAL'/>
    </map>
  </maps>
  <maps key='openstreetcam.filter.search.osmComparison'>
  </maps>
  <maps key='openstreetcam.filter.search.photoType'>
    <map>
      <tag key='name' value='PHOTO'/>
    </map>
  </maps>
  <maps key='openstreetcam.filter.search.signType'>
  </maps>
  <maps key='openstreetcam.filter.search.specificSign'>
  </maps>
  <tag key='openstreetcam.layerOpened' value='true'/>
  <tag key='openstreetcam.localVersion' value='184'/>
  <tag key='openstreetcam.panelOpened' value='true'/>
  <tag key='openstreetcam.preferences.autoplay.delay' value='2000'/>
  <tag key='openstreetcam.preferences.cache.disk' value='1000'/>
  <tag key='openstreetcam.preferences.cache.memory' value='50'/>
  <tag key='openstreetcam.preferences.cache.nearby' value='2'/>
  <tag key='openstreetcam.preferences.cache.prevNext' value='5'/>
  <tag key='openstreetcam.preferences.mapView.manualSwitch' value='true'/>
  <tag key='openstreetcam.preferences.mapView.photoZoom' value='16'/>
  <tag key='openstreetcam.preferences.mouseHover.delay' value='100'/>
  <tag key='openstreetcam.preferences.trackLoading' value='true'/>
  <tag key='openstreetcam_detection.png.lastHeight' value='20'/>
  <tag key='openstreetcam_detection.png.minimized' value='true'/>
  <tag key='openstreetcam_logo_25x25.png.geometry' value='x=372,y=63,width=1152,height=823'/>
  <tag key='openstreetcam_logo_25x25.png.lastHeight' value='200'/>
```

**Comment by beataj-telenav** [comment]
Have you tried to filter out a data while a track belonging to a selected photo/detection/aggregated detection is loaded? You can enable/disable this feature from OpenStreetCam plugin preferences -> "Load track on image selection".
The "Only mine" and "Not older than"  filters are not applicable if also the track data is displayed.
