### ISSUE TITLE
Clicking on detection in aggregated detections panel opens new photo panel, but I already have one open

### ISSUE THREAD

**Issue by mvexel** [openstreetcam/josm-plugin#35]
Reproduce (on Mac)
* Undock the OSC photo panel
* Close JOSM
* Reopen JOSM
* Click on an aggregated detection 
* In the detections list, click on a row
* A new OSC photo window (displaying the image with the detection outlined in blue) will open behind the existing one.

**Comment by beataj-telenav** [comment]
Fixed in build 236.
