### ISSUE TITLE
All images in JOSM with direction point North

### ISSUE THREAD

**Issue by pkoby** [openstreetcam/josm-plugin#37]
At some point recently, it looks like the JOSM plugin doesn't show image orientation anymore. Images that do have a direction still show an arrow on the point, but point at 0/360 degrees.
![image](https://user-images.githubusercontent.com/7786285/57476723-32bcad00-7265-11e9-9bba-8e6a876dd47e.png)

**Comment by beataj-telenav** [comment]
Thanks for reporting the issue. In which area/city are you encountering the issue?

**Comment by pkoby** [comment]
This is in the Huntington, WV, USA area at least. I just checked some other US areas and other uploaders, and it's not just my area or photos.

**Comment by beataj-telenav** [comment]
There might be an issue with the heading of the data, we will analyze it further. The plugin only displays the data received from the OpenStreetCam API.

**Comment by beataj-telenav** [comment]
Fixed in build 236.
