### ISSUE TITLE
Incompatibility with JOSM 15502+

### ISSUE THREAD

**Issue by don-vip** [openstreetcam/josm-plugin#39]
Hello,
I released JOSM tested **15492** recently, you should probably update to this version.

Right _after_ releasing it, I merged a huge patch concerning GPX, that changes some APIs:
https://josm.openstreetmap.de/changeset/15496/josm
https://josm.openstreetmap.de/changeset/15502/josm/

Currently the OpenStreetCam is the only plugin not compatible with the new API introduced in **15502**, see below;
https://josm.openstreetmap.de/jenkins/job/JOSM-Integration/3855/warnings3Result/

I understand you have right now a simple distribution model with a static URL, and you update the JAR once a new tested version of JOSM is out.

As we check daily the compatibility of the JOSM plugins with the current development version, keeping this model would mean for us daily errors for the whole month, so I'd like to propose a new model.

JOSM plugins manifest allow to specify URLs for previous versions. JOSM website parses these URLs every 10 minutes and updates https://josm.openstreetmap.de/plugin (the default plugin list) accordingly.

If you switch the current Ant build to https://github.com/floscher/gradle-josm-plugin it is very easy to specify these URLs, you have a good example with https://github.com/Gubaer/josm-contourmerge-plugin.

Would it be possible for you to do it this month? I can help if you want (and I'm sure @floscher too :) )

**Comment by beataj-telenav** [comment]
Hello,

thank you for notifying me regarding the change. When do you plan to release the new JOSM version? 
I will be out of the office between the  7-25 of November and we can plan a new release for the new JOSM version after the 25th of November. 
If you plan to release the new JOSM version earlier, we can just disable the functionality and re-add it afterwards.

**Comment by don-vip** [comment]
We stick to a monthly schedule, so next version will be released around 30/11 or 01/12.

**Comment by beataj-telenav** [comment]
We have managed to create a new version of the plugin compiled with josm latest.
