### ISSUE TITLE
JOSM Plugin to Show Date and Time Image was Taken

### ISSUE THREAD

**Issue by MikeTho16** [openstreetcam/josm-plugin#4]
Currently the plugin shows the date that the image was uploaded. It would be of greater value to know when the image was taken as many hours or even days may elapse from when I image was taken and when it was uploaded. For example, if I record a "track" on my way to work headed one direction, and another on my way home headed the opposite direction, and then upload when I get home, all images will be mixed together on the JOSM map and have the same upload date and time (thus preventing this from being used to differentiate them).

**Comment by beataj-telenav** [comment]
The issue was fixed.
