### ISSUE TITLE
Plugin can't be installed, link is 404.

### ISSUE THREAD

**Issue by squeak9** [openstreetcam/josm-plugin#53]
When I try to install the plugin i get an error:

`- 00092.385 E: org.openstreetmap.josm.plugins.PluginDownloadException: java.io.IOException: stream is closed. Cause: java.io.IOException: stream is closed`

The description on the plugin list says this: 
> Plugin provided by an external source: https://github.com/kartaview/josm-plugin/releases/latest/download/KartaView.jar

and that link is 404 so I assume that's why.

**Comment by tBeata-grab** [comment]
The issue was fixed.

**Comment by squeak9** [comment]
Thanks for the quick response!👍
