### ISSUE TITLE
Remember visible state for OSV layer

### ISSUE THREAD

**Issue by mvexel** [openstreetcam/josm-plugin#9]
If I make the OSV layer invisible in the Layer panel, quit JOSM and start JOSM again, I would expect that layer to remain invisible until I make it visible again.

**Comment by AllroadsNL** [comment]
JOSM start again. JOSM 10966
![osv](https://cloud.githubusercontent.com/assets/8817345/18691140/51755af8-7f92-11e6-8d54-b2aea8c47117.png)

**Comment by mvexel** [comment]
Thanks for the visual clarification, @AllroadsNL.

**Comment by Commodoortje** [comment]
[https://www.dropbox.com/s/svdaqfobogtwuz5/2016-09-21_01-34-16.png?raw=1](url)

**Comment by Commodoortje** [comment]
![2016-09-21_01-34-16](https://cloud.githubusercontent.com/assets/17632950/18694489/9f1fa656-7faa-11e6-810e-912b9525cc41.png)

**Comment by mvexel** [comment]
Translation of @Commodoortje 's comment above (from Dutch) --> The OpenStreetView panel should NOT open by default when starting JOSM when the user has closed it before. So remember the state of the layer visibility as well as the panel.

**Comment by martijnv-telenav** [comment]
I received another request for this through another channel. Basically we should:
* Not add the OSC layer by default when the plugin is installed.
* Remember the state of the panel and layer between JOSM sessions.

**Comment by beataj-telenav** [comment]
What is the reason behind not adding by default the OSC layer? After the user instals the plugin he/she will not be able to see any OpenStreetCam image by default. This would add an extra step for the users who expect to see by default the OpenStreetCam images.
We had already implemented the logic for remembering the state of the panel and layer between JOSM sessions.

**Comment by mvexel** [comment]
Reasoning is that privacy-conscious users would want control over when data from external sources is being downloaded. So if the layer 'just appears' after you install the plugin it would start downloading data already. See for example how Mapillary does this -- it adds an entry in the imagery menu that you need to select.

I would suggest waiting for a PR on this. If anyone wants to submit this, we'll merge.

**Comment by AllroadsNL** [comment]
I want to be fully in charge how JOSM looks like, when I open JOSM.
Plugin installed or not, if not installed, I do not want to see anything in screen and working.
A plugin must only be there to activate (one button/entry), then it should work, get data, if not activated, then not.
Privacy is a big thing. I expect that they do not collect my behavior.
I use JOSM for all different kind of sessions, not only for editing Openstreetmap ;-)
Mostly I edit Openstreetmap in that session in a different layer.
I also use it as a track designer, do not use Mapsource anymore, as a example.
Then you want certain plugins not activated.

By default:
There more session that I do want to delete the OSC layer, a step for do not want is a bigger deal then a step for i want. If I start up and it is always there, this is very annoying. In the paste Skobbler was/is very annoying. I deleted the plugin. In a lot/most of the session I do not need it.

**Comment by beataj-telenav** [comment]
Thanks for clarification. We will include this change request in the next build.

**Comment by AllroadsNL** [comment]
JOSM thing:
[ticket](https://josm.openstreetmap.de/ticket/14313#ticket)

**Comment by beataj-telenav** [comment]
Fixed a long time ago.
